# Generated by Django 3.2.13 on 2022-06-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20220623_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
